config/routes.rb
LafabMvp::Application.routes.draw do
 
  

  devise_for :accounts
  resources :users
  resources :skills
  resources :messages do
    member do
      post :new
    end
  end
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
   collection do
      get :trashbin
      post :empty_trash
   end
  end

  

  root 'welcome#index'
  get 'home' => 'welcome#home'

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user
		geocoded_by :address
		after_validation :geocode, :if => :address_changed?
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable

  include PublicActivity::Model
  tracked

  def location
  	self.user.location
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :account
	has_many :skills
	has_one :location
	
	acts_as_messageable

	

	#Returning the email address of the model if an email should be sent for this object (Message or Notification).
	#If no mail has to be sent, return nil.
	def mailboxer_email(object)
	  #Check if an email should be sent for that object
	  #if true
	  return "define_email@on_your.model"
	  #if false
	  #return nil
	end

	def upload_images (picture_path, ext)
		
		
		self.picture_name =  "profile_pic" + "_" + self.id.to_s	
		
		
		cloudinary_options = {
			:public_id => picture_name,
			:crop => :limit, :width => 2000, :height => 2000,
			:eager => [
				{ :width => 200, :height => 200, 
					:crop => :thumb, :gravity => :face,
					:radius => 20, :effect => :sepia },
					{ :width => 100, :height => 150, 
						:crop => :fit, :format => 'png' }
						],                                     
					:tags => ['profile_picture']
		}
		
		if Cloudinary::Uploader.upload picture_path, cloudinary_options
			self.picture_name =  "profile_pic" + "_" + self.id.to_s + ext
			self.save
		else
			"soucis"
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_filter :authenticate_account!
	helper_method :mailbox, :conversation
	
	def index
		@conversations ||= current_user.mailbox.inbox.all
		@user = current_user
	end

	def show
		@user = current_user	
	end

	def reply
		current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
		redirect_to conversation
	end

	
	def trash_folder     
		@trash ||= current_user.mailbox.trash.all   
	end

	def trash  
		conversation.move_to_trash(current_user)  
		redirect_to :conversations 
	end 
	def untrash  
		conversation.untrash(current_user)  
		redirect_to :back 
	end
	
	def empty_trash   
		current_user.mailbox.trash.each do |conversation|
			conversation.receipts_for(current_user).update_all(:deleted => true)
  		end
 		redirect_to :conversations
	end







private
	def current_user
		@account = current_account
		@user = User.find(@account.user_id)	
	end 

 
	def mailbox
	 @mailbox ||= current_user.mailbox
	end
	 
	def conversation
	 @conversation ||= mailbox.conversations.find(params[:id])
	end
	 
	def conversation_params(*keys)
	 fetch_params(:conversation, *keys)
	end
	 
	def message_params(*keys)
	 fetch_params(:message, *keys)
	end
	 
	def fetch_params(key, *subkeys)
	 params[key].instance_eval do
	   case subkeys.size
	   when 0 then self
	   when 1 then self[subkeys.first]
	   else subkeys.map{|k| self[k] }
	   end
	 end
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
 
  # GET /message/new
  def new
    # raise params.inspect
    @rec = User.find(params[:user_id])
    @message = current_user.messages.new
  end
 
   # POST /message/create
  def create
    @recipient = User.find(params[:user])
    current_user.send_message(@recipient, params[:body], params[:subject])
    flash[:notice] = "Message has been sent!"
    redirect_to :conversations
  end

private
  def current_user
    @account = current_account
    @user = User.find(@account.user_id) 
  end 


end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

def index
	if params[:tag]
		@skills = Skill.tagged_with(params[:tag])
	else
		@skills = Skill.all
	end
	@skills_locations = Array.new(@skills.count) { Array.new(2) }
	i = 0
	@display_position = Hash.new
	@skills.each do |skill|
		@skills_locations[i] = [skill.location.latitude, skill.location.longitude]
		@display_position[skill.id] = i + 1
		i += 1
	end
	@user_skills = false
end

def show
	@skill = Skill.find(params[:id])
	@location = @skill.location
	@bound = [@location.latitude, @location.longitude]
	@bounds = [[48.86473789999999 , 2.3898164],@bound]
	# binding.pry
end

	def edit
		@skill = Skill.find(params[:id])
	end

	def update
		@skill = Skill.find(params[:id])

		if @skill.update_attributes(skill_params)
			flash[:success] = "Profile updated"
			redirect_to @skill
		end
	end




private
  def skill_params
    params.require(:skill).permit(:title, :description, :tag_list)
  end

  def allow_update
  	
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		@users_locations = Array.new(User.count) { Array.new(2) }
		@users.each do |user|
			@users_locations[user.id - 1] = [user.location.latitude, user.location.longitude]
		end
		
	end
	def show
		@user = User.find(params[:id])
		@skills = @user.skills
		@user_skills = true
	end

	def edit
		@user = current_user
	end

	def update
		user = current_user
		
		unless params[:user][:picture].nil?
			ext = "." + params[:user][:picture].original_filename.split(".")[1]
			image_path = params[:user][:picture].path
			user.upload_images(image_path, ext)
		end

		if user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to user
		end
	end

	def edit
		@user = current_user
	end


	private

	def current_user
		@account = current_account
		@user = User.find(@account.user_id)	
	end 

	def user_params
		params.require(:user).permit(:name, :picture_name)
	end



	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if signup
  		@account = current_account
  		@user = User.create(name: "")
  		@account.user_id = @user.id
  		@account.save
  	end


  	if account_signed_in? then
	  	@account = current_account
	  	@user = User.find(@account.user_id) unless signup
	end
  end

  

  def signup
  	if current_account != nil
  		@account = current_account 
  		@account.user_id == nil 
  	else
  		signup = false
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
	def tag_links(skill)
		raw skill.tag_list.map{ |tag| link_to tag, skills_path(tag: tag), 
			class: 'label radius secondary' }.join(' ')
	end
	

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/index.html.haml
%h1= @user.name
- @conversations.each do |conversation|
	%li
	= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p")
	= link_to conversation.subject, conversation
	- conversation.participants.each do |participant|
		- if participant != @user
			= participant.name + ", "
	= link_to "Move to Trash", {:controller => "conversations", :action => "trash", :id => conversation.id}, :title=> "Move to Trash", :method=>'post' 

app/views/conversations/show.html.haml
= conversation.subject
A conversation with
- conversation.participants.each do |participant|
	- if participant != @user
		= link_to participant.name, participant
		= content_tag_for(:li, conversation.receipts_for(@user)) do |receipt|
			- message = receipt.message
			%strong= message.sender.name + " :"
			= message.body 

		= conversation.updated_at.strftime("%a, %m/%e/%Y %I:%M %p")
= render 'messages/form', conversation: conversation

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if account_signed_in? %>
    <%= link_to "Log out", destroy_account_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_account_registration_path %>
    <%= link_to "Sign in", new_account_session_path %>
  <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html{ lang: "en" }
	%head
		%meta{ charset: "utf-8" }/
		%meta{ name: "viewport", content: "width=device-width, initial-scale: 1.0" }/
		%title= content_for?(:title) ? yield(:title) : "La Fabriq"
		= stylesheet_link_tag "application"
		%link{href: "http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css", rel: "stylesheet"}/
		= javascript_include_tag "vendor/modernizr"
		%script{src: "http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"}
		
		= csrf_meta_tags
		
		

		%body.home
			= render 'shared/top_bar'

			= yield
			= javascript_include_tag "application", "data-turbolinks-track" => true	

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LafabMvp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<% if account_signed_in? %>
		<%= link_to "Log out", destroy_account_session_path, method: :delete %>
	<% else %>
		<%= link_to "Sign up", new_account_registration_path %>
		<%= link_to "Sign in", new_account_session_path %>
	<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/users.html.haml
!!!
%html{ lang: "en" }
	%head
		%meta{ charset: "utf-8" }/
		%meta{ name: "viewport", content: "width=device-width, initial-scale: 1.0" }/
		%title= content_for?(:title) ? yield(:title) : "LaFab_mvp"
		= stylesheet_link_tag "application"
		= javascript_include_tag "vendor/modernizr"
		= javascript_include_tag "application"
		= csrf_meta_tags

		%body
			
			



			= yield
				
			= debug(params)

app/views/layouts/welcome.html.haml
!!!
%html{ lang: "en" }
	%head
		%meta{ charset: "utf-8" }/
		%meta{ name: "viewport", content: "width=device-width, initial-scale: 1.0" }/
		%title= content_for?(:title) ? yield(:title) : "LaFab_mvp"
		= stylesheet_link_tag "application"
		= javascript_include_tag "vendor/modernizr"
		= javascript_include_tag "application"
		= csrf_meta_tags

		%body.home
			= render 'shared/top_bar'





			= yield
				

app/views/messages/_form.html.haml
Reply:
=form_for :message, url: [:reply, conversation] do |f|
	= f.text_area :body
	= f.submit "Send Message", class: 'btn btn-primary'
	= submit_tag 'Clear Reply Box', type: :reset, class: 'btn btn-danger'

app/views/messages/_new.html.haml
Send a message to
= @user.name
= form_tag({controller: "messages", action: "create"}, method: :post) do}
  = label_tag :subject
  = text_field_tag :subject
  = label :body, "Message text"
  = text_area_tag :body
  = hidden_field_tag(:user, "#{@user.id}")
  = submit_tag 'Send message', class: "btn btn-primary"

app/views/messages/new.html.haml
Send a message to
= @rec.name
= form_tag({controller: "messages", action: "create"}, method: "post") do
  = label_tag :subject
  = text_field_tag :subject
  = label :body, "Message text"
  = text_area_tag :body
  = hidden_field_tag(:user, @rec.id.to_s)
  = submit_tag 'Send message', class: "btn btn-primary"

app/views/shared/_menu.html.haml
.off-canvas-wrap.check
  .inner-wrap
    %nav.tab-bar
      %section.left.large-5.columns
        %h3 La Fabriq
        %h4 fabriquons du tissus économique local
      %section.middle.large-5.columns
        .row.collapse
          .large-9.small-10.columns
            %input{placeholder: "Find Stuff", type: "text"}/
          .large-3.small-2.columns
            %a.alert.button.postfix{href: "#"} Search
        .row
          .large-9.small-10.columns
            -if account_signed_in?
              = User.find(current_account.user_id).name
          .large-3.small-2.columns
            -if account_signed_in?
              = current_account.user_id

      %section.right.large-2.columns
        %a.right-off-canvas-toggle.menu-icon
          %span

          .log-stuff.check
            - if account_signed_in?
              = link_to "Log out", destroy_account_session_path, method: :delete
            - else
              = link_to "Sign up", new_account_registration_path
              = link_to "Sign in", new_account_session_path
    %aside.right-off-canvas-menu
      %ul.off-canvas-list
        %li
          %label Users
        %li
          %a{href: "#"} Hari Seldon
        \...
    %section.main-section
      / content goes here
    %a.exit-off-canvas

app/views/shared/_top_bar.html.haml
.nav.full-width
	.large-5.small-4.columns.top-menu
		.large-3.small-3.columns
			= image_tag("logo_fabriq_blanc.png",:width => 100, :height => 100)
		.large-9.small-9.columns
			%h3 La Fabriq
			%p Fabriquons du tissus économique local
	.large-5.small-5.columns.top-menu
		.row.collapse.search-bar
			.large-9.small-10.columns
				%input{placeholder: "Find Stuff", type: "text"}/
			.large-3.small-2.columns
				%a.alert.button.postfix{href: "#"} Search
	.large-2.small-3.columns.top-menu
		.row.menu-icon
			= image_tag("menu.png",:width => 50, :height => 50)
		.row.log-stuff
			- if account_signed_in?
				= link_to "Log out", destroy_account_session_path, method: :delete
			- else
				= link_to "Sign up", new_account_registration_path
				= link_to "Sign in", new_account_session_path

app/views/skills/_comment.html.haml
.panel.callout.radius
	%strong= comment.user.name
	%p= comment.content

app/views/skills/_form_skill.html.haml
= form_for @skill, url: {action: "update"}, html: {class: "nifty_form"} do |f|
	= f.label :title
	= f.text_field :title
	= f.label :description
	= f.text_field :description
	/ = f.label :tranche_age
	/ = f.text_field :tranche_age
	/ = f.label "selectionner une photo avec un beau petit sourire"
	/ = f.file_field :picture
	= f.submit "Create"

app/views/skills/_map.html.erb
<div id="map">
<script>
var map = L.map('map')
var bounds = <%= @bounds %> //=> [[lat0, lng0], [lat1, lng1]]
padded = L.latLngBounds( bounds ).pad(0.042) // returns bigger bounds
map.fitBounds(padded)


marker = L.marker(bounds[1]).addTo(map)


L.tileLayer('http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
          attribution: 'Map Data &copy; <a href="http://openstreetmap.org">OSM</a>',
          maxZoom: 20
      }).addTo(map)
</script>
</div>

app/views/skills/_map_skills.html.erb
<div id="map">
<script>
var map = L.map('map')
var bounds = <%= @skills_locations %> //=> [[lat0, lng0], [lat1, lng1]]
padded = L.latLngBounds( bounds ).pad(0.042) // returns bigger bounds
map.fitBounds(padded)

for (var i=1;i<bounds.length;i++)
{
	marker = L.marker(bounds[i],{title: i}, {alt: i}).addTo(map);
}



L.tileLayer('http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
          attribution: 'Map Data &copy; <a href="http://openstreetmap.org">OSM</a>',
          maxZoom: 20
      }).addTo(map)
</script>
</div>

app/views/skills/_skill.html.haml
%li.panel.callout.radius
	%h4= link_to skill.title, skill

	%p= skill.description
	.tag
		= tag_links(skill)
	

app/views/skills/edit.html.haml
.row
	.small-9.large-9.columns.centered
		= render "form_skill"

app/views/skills/index.html.haml
.container.full-width
	= render 'map_skills'
.row
	%h1
		= @skills.count.to_s + " competences trouvées"
	
	%ol= render @skills

app/views/skills/show.html.erb
<div id="map">
<script>
var map = L.map('map')
var bounds = <%= @bounds %> //=> [[lat0, lng0], [lat1, lng1]]
padded = L.latLngBounds( bounds ).pad(0.042) // returns bigger bounds
map.fitBounds(padded)


marker = L.marker(bounds[1]).addTo(map)


L.tileLayer('http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
          attribution: 'Map Data &copy; <a href="http://openstreetmap.org">OSM</a>',
          maxZoom: 20
      }).addTo(map)
</script>
</div>

app/views/skills/show.html.haml
.container.full-width
	= render 'map'
.row
	%li.panel.callout.radius
	%h4= @skill.title

	%p= @skill.description
	.tag
		= tag_links(@skill)

app/views/users/_form_user.html.haml
= form_for @user, url: {action: "update"}, html: {class: "nifty_form"} do |f|
	= f.label :prenom
	= f.text_field :prenom
	= f.label :nom
	= f.text_field :nom
	= f.label :tranche_age
	= f.text_field :tranche_age
	= f.label :tel_fixe
	= f.text_field :tel_fixe
	= f.label :tel_portable
	= f.text_field :tel_portable
	= f.label "selectionner une photo avec un beau petit sourire"
	= f.file_field :picture
	= f.submit "Create"

app/views/users/_map_users.html.erb
<div id="map">
<script>
var map = L.map('map')
var bounds = <%= @users_locations %> //=> [[lat0, lng0], [lat1, lng1]]
padded = L.latLngBounds( bounds ).pad(0.042) // returns bigger bounds
map.fitBounds(padded)

for (var i=1;i<bounds.length;i++)
{
	marker = L.marker(bounds[i]).addTo(map);
}



L.tileLayer('http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', {
          attribution: 'Map Data &copy; <a href="http://openstreetmap.org">OSM</a>',
          maxZoom: 20
      }).addTo(map)
</script>
</div>

app/views/users/edit.html.haml
.row
	.large-3.columns
		= cl_image_tag(@user.picture_name, :width => 100, :height => 130, :crop => :fill)
	.large-9.columns
		%h1= @user.name
.row
	.small-9.large-9.columns.centered
		= render "form_user"

app/views/users/index.html.haml
.container.full-width
	= render 'map_users'

%h1 Allez
/ .container.full-width
/ 	= render @users

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

app/views/users/show.html.haml
.row
	.large-3.columns
		= cl_image_tag(@user.picture_name, :width => 100, :height => 130, :crop => :fill)
	.large-9.columns
		%h1= @user.name
.row.check2
	.small-3.large-2.columns.sidemenu
		%ul.large-block-grid
			%li.iconmenu 
				= image_tag("people_territory.png",:width => 75, :height => 75)
			%li.iconmenu
				= link_to(image_tag("maker.png",:width => 75, :height => 75), root_path)
			%li.iconmenu 
				= image_tag("calendar.png",:width => 75, :height => 75)
			%li.iconmenu 
				= image_tag("details.png",:width => 75, :height => 75)
			%li Block Grid Item

	.small-9.large-10.columns
		%h1 competences
		
		= render @skills

.row
	.small-2.large-4.columns A
	.small-4.large-4.columns B
	.small-6.large-4.columns C

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
	<% if current_account != nil %>
		<% if @user.name != "" %>
			<%= @user.name %>
		<% else %>
				<%= form_for(@user) do |f| %>
	      
				<%= f.label "Avec mon nom c'est mieux" %>
				<%= f.text_field :name %>

				<%= f.submit "GoGOGO", class: "button [radius round]"%>
				<% end %>
		<%end%>
	<%end%>
<p>A plus dans le bus</p>

app/views/welcome/index.html.haml
%h1 Welcome#index
- if current_account != nil
	- if @user.name != ""
		= @user.name
	- else
		= form_for(@user) do |f|
			= f.label "Avec mon nom c'est mieux"
			= f.text_field :name
			= f.submit "GoGOGO", class: "button [radius round]"
%p A plus dans le bus

%ul.small-block-grid-3
	%li
		.row.prez
			.row 
				%h2 L'app de la Fabriq
			.row
				%ul
					%li Intégrer un réseau de proximité
					%li De la visibilité pour vos compétences
					%li Suivez l'actualité de votre Fabriq
					%li Intégrer les poles de compétences
					%li Trouver des compétences autour de vous
			.row 
				.large-6.columns
					= link_to "visite guidée", "#", class:"button [radius round]"
				.large-6.columns
					= link_to "Devenez FabriQant", "#", class:"button [radius round]"


	%li
		.row.prez Your content goes here
	%li
		.row.prez Your content goes here

.row.prez
	.circle
		Hello I'm circle